apiVersion: v1
kind: Pod
metadata:
  name: haiku-havoc-hero
  namespace: default
spec:
  containers:
    - name: haiku-havoc-hero
      image: mclacore/haiku-havoc-hero:latest
      imagePullPolicy: Always
      env:
        - name: POSTGRES_PASSWORD
          value: password

